In [1]:
import numpy as np

In [2]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
aa = a.reshape(3,3).astype(np.double)
aa

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [4]:
print(aa)
print(aa.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
(3, 3)


In [5]:
b = np.arange(1,4)
print(b)
print(b.shape)

[1 2 3]
(3,)


In [6]:
bb = b[np.newaxis,:]
print(bb)
print(bb.shape)

[[1 2 3]]
(1, 3)


In [7]:
bbb = b[:,np.newaxis]
print(bbb)
print(bbb.shape)
print(bbb.T)

[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]


In [8]:
aa*b

array([[  1.,   4.,   9.],
       [  4.,  10.,  18.],
       [  7.,  16.,  27.]])

In [9]:
c = np.arange(1,5)
c

array([1, 2, 3, 4])

In [10]:
d = aa*c[:,np.newaxis,np.newaxis]
print(d)
print(d.shape)

[[[  1.   2.   3.]
  [  4.   5.   6.]
  [  7.   8.   9.]]

 [[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]]

 [[  3.   6.   9.]
  [ 12.  15.  18.]
  [ 21.  24.  27.]]

 [[  4.   8.  12.]
  [ 16.  20.  24.]
  [ 28.  32.  36.]]]
(4, 3, 3)


In [11]:
e = np.ones(9).reshape(3,3)
print(e)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [12]:
d+e

array([[[  2.,   3.,   4.],
        [  5.,   6.,   7.],
        [  8.,   9.,  10.]],

       [[  3.,   5.,   7.],
        [  9.,  11.,  13.],
        [ 15.,  17.,  19.]],

       [[  4.,   7.,  10.],
        [ 13.,  16.,  19.],
        [ 22.,  25.,  28.]],

       [[  5.,   9.,  13.],
        [ 17.,  21.,  25.],
        [ 29.,  33.,  37.]]])

In [13]:
y = np.arange(1,5)
print(y)

[1 2 3 4]


In [14]:
g=((d+e).T+y).T
print(g)
print(g.shape)

[[[  3.   4.   5.]
  [  6.   7.   8.]
  [  9.  10.  11.]]

 [[  5.   7.   9.]
  [ 11.  13.  15.]
  [ 17.  19.  21.]]

 [[  7.  10.  13.]
  [ 16.  19.  22.]
  [ 25.  28.  31.]]

 [[  9.  13.  17.]
  [ 21.  25.  29.]
  [ 33.  37.  41.]]]
(4, 3, 3)


In [15]:
np.sum(g**2,axis=0)

array([[  164.,   334.,   564.],
       [  854.,  1204.,  1614.],
       [ 2084.,  2614.,  3204.]])